version: "2"
services:
  web:
    build: .
      # command: "gunicorn manage\:app"
      # ENTRYPOINT ["gunicorn", "manage:app"]
    volumes:
      - .:/code
    ports:
      - "9004:9004"
    env_file:
      - .env.default
      - .env
#     depends_on:
#       - db
#   db:
#     build: docker/postgres
#     environment:
#       - POSTGRES_PASSWORD=postgres
