version: 2
jobs:
  build:
    working_directory: ~/benj
    docker:
      - image: python:3.6.0
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run: pip install -r requirements/dev.txt

    steps:
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv benj
            . benj/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "benj"
      - run:
          command: |
            . benj/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "57:6c:6d:89:04:ba:21:96:62:1e:84:ee:da:fd:ae:c2"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              heroku run python manage.py deploy
              heroku restart
            fi
